In [1]:
import os
import sys
from pathlib import Path # if you haven't already done so
file = Path(os.path.dirname(os.path.abspath("__file__"))).resolve()
parent, root = file.parent, file.parents[1]
sys.path.append(str(root))

import torch
from dtmgp.kernels.laplace_kernel import LaplaceProductKernel

In [8]:
n = 2 # the size of x1
m = 4 # the size of x2
d = 1 # dimension of x1, x2
x1 = torch.randn(n,d)
x2 = torch.randn(m,d)
lengthscale = torch.randn(d)
print(x1)
print(x2)

tensor([[-0.0788],
        [-0.6753]])
tensor([[-0.5106],
        [-0.6129],
        [-0.1487],
        [-1.3573]])


In [9]:
kernel = LaplaceProductKernel()
kernel(x1=x1,x2=x2)

tensor([[0.6494, 0.5862, 0.9326, 0.2785],
        [0.8482, 0.9395, 0.5906, 0.5056]])