In [1]:
import os
import sys
from pathlib import Path # if you haven't already done so
file = Path(os.path.dirname(os.path.abspath("__file__"))).resolve()
parent, root = file.parent, file.parents[1]
sys.path.append(str(root))

import torch
from dtmgp.kernels.laplace_kernel import LaplaceProductKernel

In [2]:
n = 2 # the size of x1
m = 4 # the size of x2
d = 1 # dimension of x1, x2
x1 = torch.randn(n,d)
x2 = torch.randn(m,d)
lengthscale = torch.randn(d)
print(x1)
print(x2)

tensor([[ 0.8130],
        [-0.5697]])
tensor([[ 0.1709],
        [ 0.1074],
        [ 0.4897],
        [-1.6963]])


In [3]:
kernel = LaplaceProductKernel(lengthscale=1.)
kernel(x1=x1,x2=x2)

tensor([[0.5262, 0.4938, 0.7237, 0.0813],
        [0.4768, 0.5081, 0.3467, 0.3241]])