In [1]:
import os
import sys
current = os.path.dirname(os.path.realpath("__file__"))
parent = os.path.dirname(current)
sys.path.append(parent)

import torch
from dtmgp.kernels.laplace_kernel import LaplaceProductKernel, LaplaceAdditiveKernel

In [2]:
n = 2 # the size of x1
m = 4 # the size of x2
d = 1 # dimension of x1, x2
x1 = torch.randn(n,d)
x2 = torch.randn(m,d)
lengthscale = torch.randn(d)
print(x1)
print(x2)

tensor([[0.6806],
        [1.0543]])
tensor([[1.2746],
        [0.8332],
        [0.1483],
        [0.4124]])


In [3]:
kernel = LaplaceProductKernel(lengthscale=1.)
kernel(x1=x1,x2=x2)

tensor([[0.5521, 0.8585, 0.5873, 0.7647],
        [0.8023, 0.8016, 0.4041, 0.5263]])

In [5]:
kernel = LaplaceAdditiveKernel(lengthscale=1.)
kernel(x1=x1,x2=x2)

tensor([[1.8111, 1.1649, 0.5873, 0.7647],
        [1.2464, 0.8016, 0.4041, 0.5263]])